spring.application.name=authserver
# Cau hinh port
# Resource Server -> 8080
# Auth Server -> 8081
server.port=8081

# Cau hinh Auth Server
# Issuer
spring.security.oauth2.authorizationserver.issuer=http://auth-server.vn:8081

# Client 1 registration 'feclient`
spring.security.oauth2.authorizationserver.client.feclient.registration.client-id=feclient
#spring.security.oauth2.authorizationserver.client.feclient.registration.client-secret={noop}feclient-secret
# Cần mã hóa luôn client-secret vì Spring sẽ gọi Bean PasswordEncoder để so sánh secret
# Nếu không phải thực hiện cấu hình sâu hơn trong Bean PasswordEncoder
# feclient-secret -> $2y$10$CiqM4VNMa6dYxSCI/C2GY...sXH1YYKzBG3qQKMpeFFvin/PCoxIq
spring.security.oauth2.authorizationserver.client.feclient.registration.client-secret=$2y$10$CiqM4VNMa6dYxSCI/C2GY...sXH1YYKzBG3qQKMpeFFvin/PCoxIq
spring.security.oauth2.authorizationserver.client.feclient.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.feclient.registration.authorization-grant-types=authorization_code,refresh_token
spring.security.oauth2.authorizationserver.client.feclient.registration.redirect-uris=https://oauth.pstmn.io/v1/callback,http://localhost:8080,http://localhost:8888
spring.security.oauth2.authorizationserver.client.feclient.registration.scopes=openid,profile,email,artists.read,artists.write

# Client X reg
#spring.security.oauth2.authorizationserver.client.mobileAppClient.registration.client-id=appclient

# Config DB
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=sba301_se1905_authserver;encrypt=false;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=123456-aA
spring.jpa.hibernate.ddl-auto=update
# create -> tạo các bảng theo thông tin từ @Entity
# create-drop -> như trên & xóa khi app stop
# none -> ko lam gi (DB first approach)
# Thông thường, khi mới khởi tạo dự án theo code-first -> chọn create-drop
# DB ổn định rồi -> chuyển về create/update và sau đó none.

# 1 số log level để debug
logging.level.org.springframework.security=DEBUG