spring.application.name=authserver
# Cau hinh port
# Resource Server -> 8080
# Auth Server -> 8081
server.port=8081

# Cau hinh Auth Server
# Issuer
spring.security.oauth2.authorizationserver.issuer=http://auth-server.vn:8081

# Client 1 registration 'feclient`
spring.security.oauth2.authorizationserver.client.feclient.registration.client-id=feclient
spring.security.oauth2.authorizationserver.client.feclient.registration.client-secret={noop}feclient-secret
spring.security.oauth2.authorizationserver.client.feclient.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.feclient.registration.authorization-grant-types=authorization_code,refresh_token
spring.security.oauth2.authorizationserver.client.feclient.registration.redirect-uris=https://oauth.pstmn.io/v1/callback
spring.security.oauth2.authorizationserver.client.feclient.registration.scopes=openid,profile,email



# Client X reg
#spring.security.oauth2.authorizationserver.client.mobileAppClient.registration.client-id=appclient